fu:
  authentication:
    # 不需要认证的请求方法和接口URI。（不认证也不鉴权，设置为'**'）
    not-authentication:
      - '**'

server:
  port: 81

spring:
  task:
    # 异步线程池配置
    execution:
      thread-name-prefix: task-
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100
        keep-alive: 60s
        allow-core-thread-timeout: true
    # 定时任务线程池配置
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        # 默认1（开发环境一定要调整，防止线程等待）
        size: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:


logging:
  level:
    com.fu.springbootdemo.mapper: debug
